# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('priority', models.CharField(blank=True, max_length=6, null=True, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Base Tasks',
                'verbose_name': 'Base Tasks',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentTask',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.BaseTask')),
                ('send_copy_email', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('employees', models.ManyToManyField(to='people.Employee', verbose_name='Employees')),
            ],
            options={
                'verbose_name_plural': 'Development Tasks',
                'verbose_name': 'Development Task',
            },
            bases=('tasks.basetask',),
        ),
        migrations.CreateModel(
            name='OperationTask',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.BaseTask')),
                ('send_copy_email', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name_plural': 'Operation Tasks',
                'verbose_name': 'Operation Task',
            },
            bases=('tasks.basetask',),
        ),
    ]
