# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggriment',
            options={'verbose_name': 'Aggrement'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice'},
        ),
        migrations.AlterModelOptions(
            name='nda',
            options={'verbose_name': 'NDA Aggrement'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Quotation'},
        ),
    ]
