# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 05:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empbankinfo',
            name='bank_account_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(99999999999)], verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='empcontactinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='LinkedIn ID'),
        ),
    ]
