# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 04:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import people.models
import people.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSkillProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_skills', people.utils.fields.CommaSeparatedStringsField(blank=True, max_length=300, null=True, verbose_name='Primary Skills')),
                ('secondary_skills', people.utils.fields.CommaSeparatedStringsField(blank=True, max_length=300, null=True, verbose_name='Secondary Skills')),
                ('management_skills', people.utils.fields.CommaSeparatedStringsField(blank=True, max_length=300, null=True, verbose_name='Management Skills')),
                ('languages', people.utils.fields.CommaSeparatedStringsField(blank=True, max_length=300, null=True, verbose_name='Language Skills')),
            ],
            options={
                'verbose_name': 'Emplooye Skill Profile',
                'verbose_name_plural': 'Emplooye Skill Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'get_latest_by': 'created_at', 'ordering': ['-name', 'department'], 'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='empbankinfo',
            options={'ordering': ['bank_name'], 'verbose_name': 'Employees Bank Details', 'verbose_name_plural': 'Employees Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='empcontactinfo',
            options={'ordering': ['contact_email'], 'verbose_name': 'Employees Contact Information', 'verbose_name_plural': 'Employees Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='empdesignation',
            options={'ordering': ['title'], 'verbose_name': 'Designtion', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'get_latest_by': 'joined_at', 'ordering': ['-joined_date', 'first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='empmailingaddress',
            options={'ordering': ['city'], 'verbose_name': 'Employee Mailing Address', 'verbose_name_plural': 'Employee Mailing Address'},
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Department Head'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_head_mail',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Head Contact email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='empbankinfo',
            name='pan_num',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[people.models.validate_pan_number], verbose_name='PAN ID'),
        ),
        migrations.AlterField(
            model_name='empcontactinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[people.models.validate_linkedin], verbose_name='LinkedIn ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='people.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter first name of employee', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_full_name', message='Name must be Alphabetic', regex='^[a-zA-Z]*$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joined Data'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter last name of emplooye', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_full_name', message='Name must be Alphabetic', regex='^[a-zA-Z]*$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('MR', 'MARRIED'), ('S', 'SINGLE')], default='S', help_text='default will be single', max_length=2, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', verbose_name='Photo', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pref_name',
            field=models.CharField(blank=True, help_text='Enter prefered name of emplooye', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_full_name', message='Name must be Alphabetic', regex='^[a-zA-Z]*$')], verbose_name='Prefer Name'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='empbankinfo',
            table='emplooye_bank_accounts',
        ),
        migrations.AlterModelTable(
            name='empcontactinfo',
            table='emplooye_contacts',
        ),
        migrations.AlterModelTable(
            name='empdesignation',
            table='employee_designations',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='empmailingaddress',
            table='emplooye_mailing_address',
        ),
        migrations.AddField(
            model_name='empskillprofile',
            name='emplooye',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.Employee', verbose_name='Emplooye'),
        ),
    ]
