# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': 'Other'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video'},
        ),
    ]
