# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'General Event',
            },
        ),
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Board Meeting',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_due', models.DateTimeField()),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('status', models.CharField(blank=True, choices=[('P', 'Planned'), ('D', 'Delayed'), ('R', 'ToRecall'), ('F', 'Failed'), ('S', 'Success')], max_length=15, null=True, verbose_name='Status')),
                ('result_note', models.TextField(blank=True, null=True, verbose_name='Result Summary')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, choices=[('C', 'Company'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], max_length=4, null=True, verbose_name='Prefix')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email Id')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('company', models.CharField(blank=True, max_length=40, null=True, verbose_name='Company Name')),
                ('purpose', models.CharField(blank=True, help_text='upto 500 chars', max_length=500, null=True, verbose_name='Purpose')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visting_date', models.DateField(verbose_name='Visiting Date')),
                ('visitinig_time', models.DateTimeField(verbose_name='Visting Time')),
                ('result_note', models.TextField(blank=True, null=True, verbose_name='Result Summary')),
                ('meeting_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employee', verbose_name='Meeting With')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
            ],
            options={
                'verbose_name_plural': 'Email Address',
                'verbose_name': 'Email Address',
            },
        ),
        migrations.CreateModel(
            name='EmployeeVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiting_company', models.CharField(max_length=100, verbose_name='Visiting Company')),
                ('purpose', models.CharField(blank=True, help_text='upto 500 chars', max_length=500, null=True, verbose_name='Purpose')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visting_date', models.DateField(verbose_name='Meeting Date')),
                ('visiting_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meeting City')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meeting With')),
                ('contact_person_designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('result_note', models.TextField(blank=True, null=True, verbose_name='Result Summary')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employee', verbose_name='Staff Employee')),
            ],
            options={
                'verbose_name_plural': 'Employee Visits',
                'verbose_name': 'Employee visits',
            },
        ),
        migrations.CreateModel(
            name='InstituteAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name_plural': 'Phone Address',
                'verbose_name': 'Phone Address',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Institute')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Contact Email')),
                ('contact_number', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Contact Number')),
                ('address_one', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line')),
                ('street_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Name')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Pincode')),
                ('drive_date', models.DateField(verbose_name='Drive Date')),
                ('hired_candidates', models.CharField(blank=True, max_length=3, null=True, verbose_name='Total Selected Candidates')),
            ],
            options={
                'verbose_name_plural': 'Yottaasys Drives',
                'verbose_name': 'Yottaasys Drives',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.BaseEvent')),
                ('location', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Conference',
            },
            bases=('operations.baseevent',),
        ),
        migrations.CreateModel(
            name='CustomerCall',
            fields=[
                ('call_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Call')),
                ('prefix', models.CharField(blank=True, choices=[('C', 'Company'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], max_length=4, null=True, verbose_name='Prefix')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('pref_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Pref Name')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('role', models.CharField(blank=True, max_length=40, null=True, verbose_name='Role')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company Name')),
            ],
            options={
                'verbose_name_plural': 'Customer Calls',
                'verbose_name': 'Customer Calls',
            },
            bases=('operations.call', models.Model),
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.BaseEvent')),
                ('location', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Hackathon',
            },
            bases=('operations.baseevent',),
        ),
        migrations.CreateModel(
            name='InterviewCall',
            fields=[
                ('call_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Call')),
                ('prefix', models.CharField(blank=True, choices=[('C', 'Company'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], max_length=4, null=True, verbose_name='Prefix')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('pref_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Pref Name')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('role', models.CharField(blank=True, max_length=40, null=True, verbose_name='Role')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company Name')),
                ('call_for_role', models.CharField(blank=True, max_length=20, null=True, verbose_name='Interview Postion')),
            ],
            options={
                'verbose_name_plural': 'Interview Calls',
                'verbose_name': 'Interview Calls',
            },
            bases=('operations.call', models.Model),
        ),
        migrations.CreateModel(
            name='InvestorCall',
            fields=[
                ('call_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Call')),
                ('prefix', models.CharField(blank=True, choices=[('C', 'Company'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], max_length=4, null=True, verbose_name='Prefix')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('pref_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Pref Name')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('role', models.CharField(blank=True, max_length=40, null=True, verbose_name='Role')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company Name')),
            ],
            options={
                'verbose_name_plural': 'Investor Calls',
                'verbose_name': 'Investor Calls',
            },
            bases=('operations.call', models.Model),
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.BaseEvent')),
                ('location', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Outings',
            },
            bases=('operations.baseevent',),
        ),
        migrations.CreateModel(
            name='TeamLunch',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.BaseEvent')),
                ('location', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Team Lunchs',
            },
            bases=('operations.baseevent',),
        ),
        migrations.AddField(
            model_name='call',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='attending_employees',
            field=models.ManyToManyField(to='people.Employee'),
        ),
    ]
