# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customerbilling',
            options={'verbose_name': 'Customer Billing'},
        ),
        migrations.AlterModelOptions(
            name='customerinvoice',
            options={'verbose_name': 'Customer Invoice'},
        ),
        migrations.AlterModelOptions(
            name='customerproject',
            options={'verbose_name': 'Customer Project'},
        ),
        migrations.AddField(
            model_name='customer',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Alternative Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='alt_num',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Alternative Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_city',
            field=models.CharField(blank=True, help_text='Company Addres city-upto 50 chars', max_length=150, null=True, verbose_name='Company City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_country',
            field=models.CharField(blank=True, help_text='Company Addres Country-upto 50 chars', max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_domain',
            field=models.CharField(blank=True, help_text='Company domain ex:finance,manufacturing', max_length=150, null=True, verbose_name='Company Domain'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_location',
            field=models.CharField(blank=True, help_text='Company Addres location-upto 50 chars', max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Name of Customer Company', max_length=150, null=True, unique=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_pincode',
            field=models.CharField(blank=True, help_text='Company Addres pincode-upto 6 chars', max_length=6, null=True, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_state',
            field=models.CharField(blank=True, help_text='Company Addres state-upto 50 chars', max_length=50, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_street',
            field=models.CharField(blank=True, help_text='Company Addres street-upto 50 chars', max_length=50, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_type',
            field=models.CharField(blank=True, help_text='Company Type ex:startup, mnc, pvt ltd', max_length=150, null=True, verbose_name='Company Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_type',
            field=models.CharField(blank=True, choices=[('Office', 'OFFICE'), ('Personal', 'PERSONAL')], max_length=25, null=True, verbose_name='Email Type'),
        ),
    ]
