# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 11:14
from __future__ import unicode_literals

import customers.c_models.customer
import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20181029_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aggrement_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 29, 11, 14, 27, 926048, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Name of Customer Company', max_length=150, null=True, unique=True, validators=[customers.c_models.customer.validate_company_name], verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, validators=[customers.c_models.customer.validate_contact_email], verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[customers.c_models.customer.validate_contact_number], verbose_name='Contact Number'),
        ),
    ]
